
MEMORY
{
  ram : ORIGIN = 0x80000000, LENGTH = 32M
  stack: ORIGIN = 0x85000000, LENGTH = 32M
}

REGION_ALIAS("REGION_TEXT", ram);
REGION_ALIAS("REGION_RODATA", ram);
REGION_ALIAS("REGION_DATA", ram);
REGION_ALIAS("REGION_BSS", ram);
REGION_ALIAS("REGION_HEAP", ram);
REGION_ALIAS("REGION_STACK", stack);
